### PR TITLE
updated Turkish locale

### PR DESCRIPTION
**Pull request by hkan**
Current translation is sloppy. I fixed that.

### CODE REVIEW

**Comment by zpao** [comment]
:thumbsup: Thanks! My Turkish is "rusty" (aka I don't know any) but the output of Google Translate sounds a bit nicer. Thanks!

Just a quick question - are there any capitalization changes needed in the new translation in the dialog titles?

**Comment by hkan** [comment]
It doesn't need any changes, it's 100% correct. You can and should use it directly.

**Comment by hkan** [comment]
Hey @zpao! I think you forgot to merge this PR. Ping me if anything is wrong with it.

**Comment by zpao** [comment]
Thanks for the reminder! Uploaded to AMO as 2.1.2.

**Pull request merged**
